BEGIN TRANSACTION;

DROP TABLE IF EXISTS favorite_taco;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
 id BIGSERIAL PRIMARY KEY,
 firstname VARCHAR(255) NOT NULL,
 lastname VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_digest VARCHAR(255) NOT NULL
);

CREATE TABLE favorite_taco (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 rating INTEGER DEFAULT 4,
 address VARCHAR(255) NOT NULL,
 phone_number VARCHAR(255) NOT NULL,
 website VARCHAR(255) NOT NULL,
 price VARCHAR(255) NOT NULL,
 user_id INTEGER REFERENCES users(id)
);


COMMIT;
